language: node_js
node_js:
- '0.12'
- '0.10'
- iojs
sudo: false
cache:
  directories:
  - node_modules
notifications:
  email: false
  slack:
    secure: XYWyCBOQd4J2bkWr0oDLhPWhYGUiTRQCGJLv7fx2iRObSGlPChmnpXc3Zk2OTodpLSL+JOQNxby2iBg5vRe4QQp6NBIQQIkZVitrrr1lwBluB956oh75RouS9TWAtRfhOJOLHljB4BvsY10hlbF71+l1/RcLT9MoTNn/XdkSk5s3oZo3xjG+tey/OacfqmQe8cgkLYS/E5tCZ+YHOhufUARZEbqhOxEe6hU+VEZUnMgyySyZ/v0VxI/NdtDMR9CxFFDy6acuWOTzzOAEa0KHIFgrw/erHvNnkf56uJU4FF6+gZTYVdlX5++KmFP8fq5UOGBA4VsM5ctlD1p96ST21+K46YEqIqByRikgs/QCsrlpdSIt7NKyI53RDta3bXa1SseGG26hkAJLYx4Hh2LRfspi231+Vha0EUNwsFZ4PUkDY3mwX2u/NQASlq9OXV1fz1MkzTeINyURqNXcC7QD2FpEZSBRQ/TGjKSrrosRGrr/YwsI5k+nLRPOo6Bwm9FiJdebFonNZ7GysATTeJqNe2++8ut12CDirHVajEWGFQBgnFB6OZUMLat+r13BCDAqXbbqJfKMUa5ZyFY0BYNLScSD0mv+DCEyvN7VWKW/V7zm1Or7RGTbqTg3IRYRlbAAx3O8+xmh9e/xbnfjc0O8xxBBN0YKFmEdGy/vwkl175o=
deploy:
  provider: npm
  email: huangtc@outlook.com
  aqi_key:
    secure: v3tuNQnREw7tzzyNhyZu08nrfBg1TC+iwP32vU5gi5pAwwV7ebizJwgmxFDUGIo/VeRYH5JEO3nrTVULp2NIMLaDzi6SWwbFAuQCN9q6OTyNBzkHksoC7A3KVWSmJjNBLb+4VvFWxuJXjrynEzQOJIUA2vvXnlt7UELfbo2EJGtcRaNa2DWIBPzVu0qlKHIF00BG/3wAx8hA3T8p3LchTjNXy7nbU/bFp6ZH2sscT6h7DHKHgo0d944lfFJCRjOQXi736nv5uvc4wswfMXiw38OYFriW1dwAeLx6aaXlAKMvK8mqv/jYYcIjzHQQerRTsd96SDXPlauvP5wGycqDB3B6+PB7HlhqBZgE4n3awczkKQ7ySZcm2skxNdDQqDj1jgSKoXBZMU1RQHzWEpf7/AvqK7NEEtjP92gG0mMZyu28c7b7RysxVF7IBKTjdgP98XPWAJ7nd0D8GiIzInJz2Ox0I6EdC7aCZjR6D1Xux2TcyUcwyYGTfwTZ/tcgRBVpe3jdw8Sc5oUsH9lJxoikDzsmSp4+A8G6A5Jt3SAGbTvL3tDQlxAkJ3Zzi897XEjayU1imVxrM5H5CzY1vWP/PoDiTz+XZdSizwpgPgCAieN5rSP+lqXZzb+LaC1UmTG3inzzvl9fN6WWk2mfv2SzurCax8E6d8KOr3a6TlVk1tk=
  on:
    tags: true
    repo: ctgnauh/hubot-lucky
